### ISSUE TITLE
Add internal dessert code names?

### ISSUE THREAD

**Issue by fat-tire** [ebelinski/apilevels#1]
According to [this story on xda](https://www.xda-developers.com/google-android-13-t-tiramisu-dessert-name/), Android 10, 11, and 12 do have internal dessert names:

Android 10: Quince Tart
Android 11: Red Velvet Cake
Android 12: Snow Cone

**Comment by ebelinski** [comment]
I like this idea. Maybe the codenames for these three should be added, along with a footnote that clarifies that these are internal codenames only? Relatedly, do you know if any versions of Android before Android 10 have a different public and private codename?

**Comment by arkon** [comment]
And the next one is Tiramisu.

**Comment by ebelinski** [comment]
I went ahead and added the Android 10, 11, and 13 internal codenames, so I'm going to go ahead and close this issue. I'm open to the idea of adding Android 13/Tiramisu, but it feels a little early? In any case I opened issue #3 for that.
