### ISSUE TITLE
Indicate minimum required target SDKs?

### ISSUE THREAD

**Issue by TWiStErRob** [ebelinski/apilevels#17]
https://developer.android.com/google/play/requirements/target-sdk

> Starting in November 2021, app updates will be required to target API level 30 or above and adjust for behavioral changes in Android 11.

> Wear OS apps must continue to target API level 28 or higher.

https://support.google.com/googleplay/android-developer/answer/9859152?visit_id=637837433771855271-4058277606&rd=1#targetsdk&zippy=%2Ctarget-api-level-requirements-for-play-console

> Android 11 (API level 30)* | 2 August 2021: Required for new apps, 1 November 2021: Required for app updates

So
 * tag API 28: as Wear OS minimum target.
 * tag API 30: as Required App minimum target

**Comment by ebelinski** [comment]
Good catch, I've updated the site to show targetSDK 28 as the requirement for Wear OS apps.

**Comment by TWiStErRob** [comment]
They just updated the page: https://support.google.com/googleplay/android-developer/answer/11926878

And with news:
> To provide users with a safe and secure experience, we are expanding on Google Play’s target API level requirements to include existing apps that aren’t updated. Apps that don’t target an API level within two years of the latest major Android version release will not be available on Google Play to new users whose devices run the latest versions of Android. Developers can request a six-month extension if more time for migration is needed.

**Comment by ebelinski** [comment]
Good catch. I updated the website to reflect the upcoming level 31 requirement for new apps by August 2022 and app updates by November 2022. 

I haven't yet added the third requirement for "existing apps" to adopt level 31 by November 1, _2023_, or the similar one requiring existing apps to adopt level 30 by November 1, 2022. Is this the first time Google is imposing a requirement like this? The details on it seem pretty surprising:

> Your app will not be available on Google Play to new users with devices running Android OS versions newer than your app’s target API level. This means that new users will not be able to discover or install your app from Google Play.
> 
> Users who have previously installed your app from Google Play will continue to be able to discover, re-install, and use your app. They will still have access to your app even if they move to a new Android device.

**Comment by TWiStErRob** [comment]
Yes, it's new. The quote I added is from the "Google Play Developer Program Policy Update" email sent out this evening.

**Comment by ebelinski** [comment]
Hmm, I see...interesting. I wonder if Google is doing this to get rid of crufty old apps on the play store. I think Apple did something similar at least once before.

**Comment by ebelinski** [comment]
Ok, I updated the site again with the new target SDK requirements for existing apps as well.

**Comment by TWiStErRob** [comment]
Thanks for the quick turnaround.
