### ISSUE TITLE
Screen size for mobile

### ISSUE THREAD

**Issue by ravener** [ebelinski/apilevels#23]
On mobile browsers the table extends beyond the page boundaries and ruins the viewport width.

![Screenshot_20220608_211435_mark via gp](https://user-images.githubusercontent.com/31079629/172671863-3f9b45f2-9748-4f37-a877-d8ce236ec20e.jpg)

In the screenshot I did zoom out, the page starts zoomed in initially.

Would be better if the table scrolled horizontally on mobile displays.

**Comment by ebelinski** [comment]
Hi @ravener, thank you for pointing out this issue. I have updated the table to scroll horizontally on smaller screens. Please let me know if this fixes the problem or if anything else needs to be changed.

**Comment by ravener** [comment]
It's much better now, however all the tables on the page scroll at the same time now, like including the "definitions" and "code files" sections. Thing is those two tables are already sized to fit the screen so it scrolls to a blank area.

**Comment by ravener** [comment]
![Screenshot_20220611_194006_mark via gp](https://user-images.githubusercontent.com/31079629/173193520-0a6a4232-08b9-4680-ad8e-3e7d22bd97ec.jpg)

Here's anther screenshot to demonstrate, this is after applying some scroll, notice the second table is also scrolling towards a blank area, meanwhile without any scroll they fit the screen and does not require scrolling. (It may or may not require scrolling on different screen sizes? Frontend dev is such a pain)

**Comment by ebelinski** [comment]
@ravener Oops haha, yeah I closed the div at the wrong table. I updated it now, I wrapped each table with `table-responsive` separately, which should mean that the smaller two tables won't scroll at all for mobile, unless more columns get added in the future.

**Comment by ravener** [comment]
@ebelinski Thanks! It looks perfect now. Closing this now.
