### ISSUE TITLE
Android 13 is released

### ISSUE THREAD

**Issue by ybbarng** [ebelinski/apilevels#27]
![스크린샷 2022-08-16 오전 11 14 57](https://user-images.githubusercontent.com/1793950/184784061-54ae22a7-a1ac-48b2-9a91-fdcd217b0d35.png)

**Comment by TWiStErRob** [comment]
https://developer.android.com/about/versions/13

**Comment by ebelinski** [comment]
Thanks for the heads up @ybbarng and @TWiStErRob. I've updated the site to reflect the release of Android 13. Let me know if there's anything specific I missed!

**Comment by ybbarng** [comment]
@ebelinski Thank you very much!
