### ISSUE TITLE
Version Code "JELLYBEAN" needs to be replaced with "JELLY_BEAN"

### ISSUE THREAD

**Issue by ybbarng** [ebelinski/apilevels#28]
Hello, I found that the version code of Jellybean text is different from [Build.VERSION_CODES](https://developer.android.com/reference/kotlin/android/os/Build.VERSION_CODES)

[JELLY_BEAN](https://developer.android.com/reference/kotlin/android/os/Build.VERSION_CODES#JELLY_BEAN:kotlin.Int), [JELLY_BEAN_MR1](https://developer.android.com/reference/kotlin/android/os/Build.VERSION_CODES#JELLY_BEAN_MR1:kotlin.Int), [JELLY_BEAN_MR2](https://developer.android.com/reference/kotlin/android/os/Build.VERSION_CODES#JELLY_BEAN_MR2:kotlin.Int) are exist in [Build.VERSION_CODES](https://developer.android.com/reference/kotlin/android/os/Build.VERSION_CODES), but the apilevels pages shows them as JELLYBEAN, JELLYBEAN_MR1, JELLYBEAN_MR2.

I think they needs to be changed to match the names in SDK.

**Comment by ebelinski** [comment]
Good catch, thanks @ybbarng! I have fixed the Jelly Bean version codes.
