### ISSUE TITLE
json/xml

### ISSUE THREAD

**Issue by kopax-polyconseil** [ebelinski/apilevels#29]
HTML is not good for progamming api level to platform version, it would be nice to have a better api to do so

Thanks for sharing!

**Comment by TWiStErRob** [comment]
What is your use case? I don't think this website's data is useful for anything other than humans :)

In code you would simply use https://developer.android.com/reference/kotlin/android/os/Build.VERSION_CODES, for an example look at the code in the [this question](https://stackoverflow.com/q/47480732/253468).

**Comment by ebelinski** [comment]
Thank you for the suggestion but since the intention of this website is to be human readable without APIs, I think I'm going to keep it the way it is for now :)
