### ISSUE TITLE
Add Android 13 information

### ISSUE THREAD

**Issue by ebelinski** [ebelinski/apilevels#3]
Android 13 has an internal codename already (Tiramisu) but it still feels a little early to add it to the site.

Information:

* Version: Android 13
* API level: 32
* Version code: `T`
* Codename: Tiramisu (internal)

Sources:

* https://www.xda-developers.com/google-android-13-t-tiramisu-dessert-name/

**Comment by oliverspryn** [comment]
It would be API 32, most likely. 31 is Android 12.

**Comment by upintheairsheep** [comment]
API level 33
