### ISSUE TITLE
year data

### ISSUE THREAD

**Issue by 1268** [ebelinski/apilevels#37]
where are you getting the year data?

**Comment by TWiStErRob** [comment]
See footnote 1. from the **Cumulative usage** column: https://apilevels.com/#fn:1 for where the usage data comes from.

The **Year** column is not related to the usage, but rather the release date of the version in that row, see https://en.wikipedia.org/wiki/Android_version_history.

**Comment by 1268** [comment]
cool thanks - I think it would be helpful to add the Wikipedia link to the page, since it is the source of that data

**Comment by TWiStErRob** [comment]
Sorry, that's not necessarily the source, I was just showing where to get more details.

It could be also the Javadoc of [`android.os.Build.VERSION_CODES`](https://developer.android.com/reference/android/os/Build.VERSION_CODES#constants_1). If @ebelinski decides to add anything it should be probably that. Although in recent years Google got a bit lazy on with the docs there.

I'm curious, what is the reason for you query?

**Comment by 1268** [comment]
> I'm curious, what is the reason for you query?

I wanted to compare the years of the API versions with the years of the different versions of Google Play Store, and I noticed that the years for the API versions were not sourced. I dont like "magic" numbers, so I think its good to at least clarify where the data came from.

**Comment by TWiStErRob** [comment]
Thanks! Raised a PR: https://github.com/ebelinski/apilevels/pull/38, double-checked: each year matches VERSION_CODES + found blog posts for latter releases. Do you think this works?

> I dont like "magic" numbers

Have to mention your username here... 😜

**Comment by 1268** [comment]
looks great, thank you
