### ISSUE TITLE
Android 14 was released, so value "TBD" in column "Year" can be replaced with "2023"

### ISSUE THREAD

**Issue by MDecker-MobileComputing** [ebelinski/apilevels#39]
Sources:
* https://android-developers.googleblog.com/2023/10/android-14-is-live-in-aosp.html
* https://arstechnica.com/gadgets/2023/10/android-14-officially-releases-for-pixel-phones/

**Comment by TWiStErRob** [comment]
PR: https://github.com/ebelinski/apilevels/pull/40

Additional source (that's in line with previous links on the page): https://blog.google/products/android/android-14/

**Comment by MDecker-MobileComputing** [comment]
Thank you for the quick fix.

**Comment by TWiStErRob** [comment]
Thanks for the alert. I was just researching when's the next stable is coming last week.
